# Generated by Django 5.1.4 on 2025-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
    ]
